In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r"C:\Users\31405.ISBDOMAIN1\Downloads\NFIP\nfip-flood-policies.csv", low_memory=False)
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50406944 entries, 0 to 50406943
Data columns (total 45 columns):
 #   Column                              Non-Null Count     Dtype
---  ------                              --------------     -----
 0   agriculturestructureindicator       11483631 non-null  object
 1   basefloodelevation                  16770184 non-null  float64
 2   basementenclosurecrawlspacetype     50406141 non-null  float64
 3   cancellationdateoffloodpolicy       6792886 non-null   object
 4   censustract                         49939824 non-null  float64
 5   condominiumindicator                50406937 non-null  object
 6   construction                        50406930 non-null  object
 7   countycode                          50357944 non-null  float64
 8   crsdiscount                         50406943 non-null  float64
 9   deductibleamountinbuildingcoverage  49744950 non-null  object
 10  deductibleamountincontentscoverage  44845359 non-null  object
 11  elevatedbuildingindicator           50406685 non-null  object
 12  elevationcertificateindicator       17800546 non-null  object
 13  elevationdifference                 50406943 non-null  float64
 14  federalpolicyfee                    50406943 non-null  float64
 15  floodzone                           50237798 non-null  object
 16  hfiaasurcharge                      50406943 non-null  float64
 17  houseofworshipindicator             15930692 non-null  object
 18  latitude                            50068244 non-null  float64
 19  locationofcontents                  35017176 non-null  object
 20  longitude                           50068244 non-null  float64
 21  lowestadjacentgrade                 15466364 non-null  float64
 22  lowestfloorelevation                17346341 non-null  float64
 23  nonprofitindicator                  15913849 non-null  object
 24  numberoffloorsininsuredbuilding     50244642 non-null  float64
 25  obstructiontype                     9777873 non-null   object
 26  occupancytype                       50406937 non-null  float64
 27  originalconstructiondate            50226625 non-null  object
 28  originalnbdate                      50406943 non-null  object
 29  policycost                          50406943 non-null  float64
 30  policycount                         50406943 non-null  float64
 31  policyeffectivedate                 50406943 non-null  object
 32  policyterminationdate               50406943 non-null  object
 33  policytermindicator                 50406940 non-null  float64
 34  postfirmconstructionindicator       50226667 non-null  object
 35  primaryresidenceindicator           50385059 non-null  object
 36  propertystate                       50406943 non-null  object
 37  reportedzipcode                     50406936 non-null  object
 38  ratemethod                          49503976 non-null  object
 39  regularemergencyprogramindicator    50406941 non-null  object
 40  reportedcity                        50406932 non-null  object
 41  smallbusinessindicatorbuilding      16955795 non-null  object
 42  totalbuildinginsurancecoverage      50406943 non-null  float64
 43  totalcontentsinsurancecoverage      50406943 non-null  float64
 44  totalinsurancepremiumofthepolicy    50406943 non-null  float64
dtypes: float64(20), object(25)
memory usage: 16.9+ GB

In [3]:
df= df[df['propertystate']=='CA']
df.shape

(2772778, 45)

In [4]:
df

,agriculturestructureindicator,basefloodelevation,basementenclosurecrawlspacetype,cancellationdateoffloodpolicy,censustract,condominiumindicator,construction,countycode,crsdiscount,deductibleamountinbuildingcoverage,...,primaryresidenceindicator,propertystate,reportedzipcode,ratemethod,regularemergencyprogramindicator,reportedcity,smallbusinessindicatorbuilding,totalbuildinginsurancecoverage,totalcontentsinsurancecoverage,totalinsurancepremiumofthepolicy
15,NaN,NaN,0.0,NaN,6.067007e+09,N,N,6067.0,0.00,1,...,Y,CA,95835,7,R,SACRAMENTO,NaN,250000.0,100000.0,335.0
23,NaN,NaN,0.0,2017-01-26,6.067007e+09,N,N,6067.0,0.00,0,...,Y,CA,95835,7,R,SACRAMENTO,NaN,250000.0,100000.0,335.0
24,NaN,302.8,0.0,NaN,6.107002e+09,N,N,6107.0,0.00,1,...,Y,CA,93277,1,R,VISALIA,NaN,250000.0,0.0,292.0
27,NaN,NaN,0.0,NaN,6.077001e+09,N,N,6077.0,0.00,1,...,Y,CA,95204,7,R,STOCKTON,NaN,150000.0,60000.0,283.0
98,NaN,6.0,0.0,NaN,6.037578e+09,N,N,6037.0,0.15,0,...,N,CA,90803,1,R,LONG BEACH,NaN,250000.0,0.0,343.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50406867,N,1.0,0.0,NaN,6.085501e+09,N,N,6085.0,0.15,2,...,Y,CA,95116,B,R,SAN JOSE,N,250000.0,0.0,259.0
50406877,N,NaN,0.0,NaN,6.067007e+09,N,N,6067.0,0.00,F,...,Y,CA,95835,7,R,SACRAMENTO,N,250000.0,100000.0,376.0
50406895,N,NaN,0.0,NaN,6.073021e+09,N,N,6073.0,0.10,F,...,N,CA,92004,1,R,BORREGO SPGS,N,241700.0,0.0,1074.0
50406913,NaN,NaN,0.0,NaN,6.037197e+09,N,N,6037.0,0.00,F,...,N,CA,90039,7,R,LOS ANGELES,N,250000.0,100000.0,374.0
50406941,N,NaN,0.0,NaN,6.059063e+09,N,N,6059.0,0.00,F,...,N,CA,92661,NaN,R,NEWPORT BEACH,N,250000.0,100000.0,310.0

In [7]:
df['floodzone'].value_counts()

X      1227671
AE      357908
A       236349
AO      213692
A99     187403
AOB     133648
C       111109
AH       89661
B        74821
AHB      31770
A01      16754
D        13522
A04       8819
A05       8075
A02       7505
A06       6975
A07       6879
AR        5645
VE        4365
A09       4003
A03       3805
A08       3496
A11       2301
A14       2147
A28       1871
A22       1747
A21       1142
A12        913
A10        906
A23        896
V05        759
A16        676
A13        609
V          575
A15        554
A20        510
V04        465
A30        449
A18        370
A17        362
A27        222
A0B        203
V06        203
A25        153
A24        143
V08        143
V01        118
A26        114
A19         98
V15         69
V07         62
V10         36
V02         30
V03         28
A00          9
E            1
Name: floodzone, dtype: int64

In [8]:
df= df[df['countycode'].notna()]
df= df[df['floodzone'].notna()]
df.reset_index(inplace=True, drop=True)

In [9]:
df

,agriculturestructureindicator,basefloodelevation,basementenclosurecrawlspacetype,cancellationdateoffloodpolicy,censustract,condominiumindicator,construction,countycode,crsdiscount,deductibleamountinbuildingcoverage,...,primaryresidenceindicator,propertystate,reportedzipcode,ratemethod,regularemergencyprogramindicator,reportedcity,smallbusinessindicatorbuilding,totalbuildinginsurancecoverage,totalcontentsinsurancecoverage,totalinsurancepremiumofthepolicy
0,NaN,NaN,0.0,NaN,6.067007e+09,N,N,6067.0,0.00,1,...,Y,CA,95835,7,R,SACRAMENTO,NaN,250000.0,100000.0,335.0
1,NaN,NaN,0.0,2017-01-26,6.067007e+09,N,N,6067.0,0.00,0,...,Y,CA,95835,7,R,SACRAMENTO,NaN,250000.0,100000.0,335.0
2,NaN,302.8,0.0,NaN,6.107002e+09,N,N,6107.0,0.00,1,...,Y,CA,93277,1,R,VISALIA,NaN,250000.0,0.0,292.0
3,NaN,NaN,0.0,NaN,6.077001e+09,N,N,6077.0,0.00,1,...,Y,CA,95204,7,R,STOCKTON,NaN,150000.0,60000.0,283.0
4,NaN,6.0,0.0,NaN,6.037578e+09,N,N,6037.0,0.15,0,...,N,CA,90803,1,R,LONG BEACH,NaN,250000.0,0.0,343.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2772712,N,1.0,0.0,NaN,6.085501e+09,N,N,6085.0,0.15,2,...,Y,CA,95116,B,R,SAN JOSE,N,250000.0,0.0,259.0
2772713,N,NaN,0.0,NaN,6.067007e+09,N,N,6067.0,0.00,F,...,Y,CA,95835,7,R,SACRAMENTO,N,250000.0,100000.0,376.0
2772714,N,NaN,0.0,NaN,6.073021e+09,N,N,6073.0,0.10,F,...,N,CA,92004,1,R,BORREGO SPGS,N,241700.0,0.0,1074.0
2772715,NaN,NaN,0.0,NaN,6.037197e+09,N,N,6037.0,0.00,F,...,N,CA,90039,7,R,LOS ANGELES,N,250000.0,100000.0,374.0
2772716,N,NaN,0.0,NaN,6.059063e+09,N,N,6059.0,0.00,F,...,N,CA,92661,NaN,R,NEWPORT BEACH,N,250000.0,100000.0,310.0

In [10]:
df.head()

,agriculturestructureindicator,basefloodelevation,basementenclosurecrawlspacetype,cancellationdateoffloodpolicy,censustract,condominiumindicator,construction,countycode,crsdiscount,deductibleamountinbuildingcoverage,...,primaryresidenceindicator,propertystate,reportedzipcode,ratemethod,regularemergencyprogramindicator,reportedcity,smallbusinessindicatorbuilding,totalbuildinginsurancecoverage,totalcontentsinsurancecoverage,totalinsurancepremiumofthepolicy
0,NaN,NaN,0.0,NaN,6.067007e+09,N,N,6067.0,0.00,1,...,Y,CA,95835,7,R,SACRAMENTO,NaN,250000.0,100000.0,335.0
1,NaN,NaN,0.0,2017-01-26,6.067007e+09,N,N,6067.0,0.00,0,...,Y,CA,95835,7,R,SACRAMENTO,NaN,250000.0,100000.0,335.0
2,NaN,302.8,0.0,NaN,6.107002e+09,N,N,6107.0,0.00,1,...,Y,CA,93277,1,R,VISALIA,NaN,250000.0,0.0,292.0
3,NaN,NaN,0.0,NaN,6.077001e+09,N,N,6077.0,0.00,1,...,Y,CA,95204,7,R,STOCKTON,NaN,150000.0,60000.0,283.0
4,NaN,6.0,0.0,NaN,6.037578e+09,N,N,6037.0,0.15,0,...,N,CA,90803,1,R,LONG BEACH,NaN,250000.0,0.0,343.0

In [11]:
df.columns

Index(['agriculturestructureindicator', 'basefloodelevation',
       'basementenclosurecrawlspacetype', 'cancellationdateoffloodpolicy',
       'censustract', 'condominiumindicator', 'construction', 'countycode',
       'crsdiscount', 'deductibleamountinbuildingcoverage',
       'deductibleamountincontentscoverage', 'elevatedbuildingindicator',
       'elevationcertificateindicator', 'elevationdifference',
       'federalpolicyfee', 'floodzone', 'hfiaasurcharge',
       'houseofworshipindicator', 'latitude', 'locationofcontents',
       'longitude', 'lowestadjacentgrade', 'lowestfloorelevation',
       'nonprofitindicator', 'numberoffloorsininsuredbuilding',
       'obstructiontype', 'occupancytype', 'originalconstructiondate',
       'originalnbdate', 'policycost', 'policycount', 'policyeffectivedate',
       'policyterminationdate', 'policytermindicator',
       'postfirmconstructionindicator', 'primaryresidenceindicator',
       'propertystate', 'reportedzipcode', 'ratemethod',
       'regularemergencyprogramindicator', 'reportedcity',
       'smallbusinessindicatorbuilding', 'totalbuildinginsurancecoverage',
       'totalcontentsinsurancecoverage', 'totalinsurancepremiumofthepolicy'],
      dtype='object')

In [12]:
df.shape

(2772717, 45)

In [14]:
for i in df.columns:
    print(i)
    print(df[i].value_counts())
    print()

agriculturestructureindicator
N    543899
Y      3294
Name: agriculturestructureindicator, dtype: int64

basefloodelevation
1.0       115280
0.0        26442
2.0        25536
9.0         9895
6.0         9102
           ...
292.3          1
623.2          1
605.8          1
1536.3         1
3111.6         1
Name: basefloodelevation, Length: 7106, dtype: int64

basementenclosurecrawlspacetype
0.0    2446686
2.0     110299
3.0     101389
1.0      61273
4.0      53054
Name: basementenclosurecrawlspacetype, dtype: int64

cancellationdateoffloodpolicy
2017-01-01    814
2017-01-04    781
2017-01-03    589
2013-09-06    451
2018-09-06    437
             ...
2009-07-11      1
2009-03-10      1
2009-05-02      1
2009-02-21      1
2009-05-31      1
Name: cancellationdateoffloodpolicy, Length: 3851, dtype: int64

censustract
6.067007e+09    28339
6.067007e+09    25411
6.067007e+09    21182
6.067007e+09    19188
6.067007e+09    17078
                ...
6.037433e+09        1
6.037408e+09        1
6.019001e+09        1
6.037433e+09        1
6.037222e+09        1
Name: censustract, Length: 7718, dtype: int64

condominiumindicator
N    2665247
U      85404
L      17384
H       4560
A        121
Name: condominiumindicator, dtype: int64

construction
N    2770230
Y       2487
Name: construction, dtype: int64

countycode
6067.0    609368
6037.0    228084
6059.0    221737
6085.0    169382
6107.0    100720
6073.0     99846
6077.0     90953
6041.0     86184
6111.0     86093
6101.0     74601
6065.0     73312
6081.0     70168
6047.0     69022
6029.0     65061
6113.0     63046
6071.0     59961
6013.0     59502
6001.0     45314
6083.0     43673
6097.0     42145
6115.0     41811
6087.0     41332
6095.0     36264
6007.0     28721
6053.0     26121
6019.0     25145
6079.0     24766
6033.0     23238
6055.0     22095
6061.0     15904
6089.0     14189
6099.0     14174
6103.0     13906
6039.0     12159
6023.0     11498
6045.0      8458
6011.0      8254
6021.0      7062
6017.0      5483
6093.0      5281
6031.0      4672
6009.0      3520
6057.0      2375
6005.0      2325
6015.0      2196
6069.0      1986
6063.0      1964
6051.0      1674
6035.0      1593
6105.0      1271
6049.0      1076
6091.0       974
6075.0       952
6025.0       880
6109.0       613
6027.0       561
6003.0        52
Name: countycode, dtype: int64

crsdiscount
0.00    1977602
0.15     290140
0.10     242445
0.05     122663
0.20      94457
0.25      24810
0.35       8121
0.30       7058
0.40       4169
0.45       1252
Name: crsdiscount, dtype: int64

deductibleamountinbuildingcoverage
1    1008702
F     710675
5     506469
2     280641
0     113284
A      52194
3      23356
E      19089
D      13980
G      12664
4       8058
C       1413
B        987
Name: deductibleamountinbuildingcoverage, dtype: int64

deductibleamountincontentscoverage
1    771788
0    654235
F    618860
2     56470
5     49335
A      9051
3      4311
G      4167
E      4115
D      1780
4      1413
C       339
B       241
Name: deductibleamountincontentscoverage, dtype: int64

elevatedbuildingindicator
N    2413391
Y     359285
Name: elevatedbuildingindicator, dtype: int64

elevationcertificateindicator
1    506197
3    167571
2    108597
4     57011
E       408
B       317
A        58
C        51
D        46
Name: elevationcertificateindicator, dtype: int64

elevationdifference
 999.0    2351181
 0.0       121991
 1.0       107111
 2.0        65355
 3.0        28361
           ...
-100.0          1
 443.0          1
 388.0          1
 569.0          1
-97.0           1
Name: elevationdifference, Length: 353, dtype: int64

federalpolicyfee
 40.0      483137
 50.0      386182
 25.0      363218
 20.0      345085
 22.0      312021
 35.0      205208
 0.0       182789
 44.0      178253
 45.0      152766
 13.0      144882
 80.0        2564
 150.0       2543
 200.0       2426
 400.0       2412
 175.0       1243
 70.0        1148
 220.0       1052
 88.0         891
 135.0        778
 440.0        762
 360.0        762
 800.0        661
 840.0        363
 385.0        339
 2000.0       288
 484.0        280
 720.0        207
 924.0        165
 735.0        140
 1800.0        94
-25.0          20
 24.0           5
 23.0           4
 19.0           3
 21.0           3
 11.0           2
 7.0            2
-10.0           2
 100.0          2
-23.0           1
 75.0           1
-22.0           1
-1.0            1
-50.0           1
 8.0            1
-8.0            1
 17.0           1
 46.0           1
 10.0           1
 3.0            1
 5.0            1
 36.0           1
 52.0           1
 12.0           1
Name: federalpolicyfee, dtype: int64

floodzone
X      1227660
AE      357907
A       236348
AO      213691
A99     187403
AOB     133648
C       111081
AH       89661
B        74821
AHB      31770
A01      16754
D        13522
A04       8819
A05       8075
A02       7505
A06       6975
A07       6879
AR        5645
VE        4365
A09       4003
A03       3805
A08       3496
A11       2301
A14       2147
A28       1871
A22       1747
A21       1142
A12        913
A10        906
A23        896
V05        759
A16        676
A13        609
V          575
A15        554
A20        510
V04        465
A30        449
A18        370
A17        362
A27        222
A0B        203
V06        203
A25        153
A24        143
V08        143
V01        118
A26        114
A19         98
V15         69
V07         62
V10         36
V02         30
V03         28
A00          9
E            1
Name: floodzone, dtype: int64

hfiaasurcharge
 0.0      1722302
 25.0      689949
 250.0     359176
-225.0         51
-200.0         50
           ...
 162.0          1
 120.0          1
-37.0           1
-228.0          1
 195.0          1
Name: hfiaasurcharge, Length: 391, dtype: int64

houseofworshipindicator
N    889083
Y     13356
0         1
9         1
8         1
Name: houseofworshipindicator, dtype: int64

latitude
38.6    305242
38.5    189946
38.7    175881
33.7    137936
38.0    128034
         ...
41.1       581
41.0       560
41.4       149
32.5       143
42.0       125
Name: latitude, Length: 96, dtype: int64

locationofcontents
Lowest floor only above ground level (No basement/enclosure/crawlspace/subgrade crawlspace)                 924476
Lowest floor above ground level and higher floors (No basement/enclosure/crawlspace/subgrade crawlspace)    428710
Basement/Enclosure/Crawlspace/Subgrade Crawlspace and above                                                 156265
Manufactured (mobile) home or travel trailer on foundation                                                   15748
Above ground level more than one full floor                                                                   9236
Basement/Enclosure/Crawlspace/Subgrade Crawlspace only                                                         104
Name: locationofcontents, dtype: int64

longitude
-121.5    472748
-121.4    150672
-121.6    130702
-121.9    107143
-122.1    105681
           ...
-115.7        19
-114.4        15
-124.4         7
-115.8         6
-114.2         5
Name: longitude, Length: 96, dtype: int64

lowestadjacentgrade
0.0       103661
1.0         4011
2.0         1507
5.0         1134
10.0         894
           ...
532.8          1
630.0          1
379.3          1
3144.7         1
3112.0         1
Name: lowestadjacentgrade, Length: 9386, dtype: int64

lowestfloorelevation
2.0       35583
1.0       28674
1.5       11183
0.5        7476
3.0        6303
          ...
2326.1        1
6008.6        1
6763.9        1
630.2         1
511.8         1
Name: lowestfloorelevation, Length: 9310, dtype: int64

nonprofitindicator
N    898885
Y      1258
Name: nonprofitindicator, dtype: int64

numberoffloorsininsuredbuilding
1.0    1650846
2.0     967753
3.0     113381
5.0      24268
4.0      15970
6.0        498
Name: numberoffloorsininsuredbuilding, dtype: int64

obstructiontype
10    145656
50    128988
15     76694
60     35187
80     18551
*      10996
54      6319
70      1051
30       516
20       140
92       122
40        95
34        40
24        13
96        12
90        11
0          2
Name: obstructiontype, dtype: int64

occupancytype
1.0    2346246
4.0     140148
2.0     126353
3.0     102679
6.0      57291
Name: occupancytype, dtype: int64

originalconstructiondate
1960-01-01    41437
1950-01-01    39811
1980-01-01    35995
1955-01-01    34697
1970-01-01    32893
              ...
1935-11-12        1
1948-12-18        1
1974-04-07        1
1985-09-11        1
2019-05-23        1
Name: originalconstructiondate, Length: 25054, dtype: int64

originalnbdate
2015-11-25    6571
2015-11-26    6184
2015-11-27    5225
2009-01-04    5162
2015-12-02    4835
              ...
1989-03-19       1
1986-12-31       1
1989-07-27       1
1987-11-10       1
2019-10-10       1
Name: originalnbdate, Length: 11922, dtype: int64

policycost
450.0      179797
365.0      128329
348.0       97909
414.0       83824
430.0       80143
            ...
7528.0          1
13186.0         1
6555.0          1
9326.0          1
7126.0          1
Name: policycost, Length: 11695, dtype: int64

policycount
1.0      2751277
4.0         4839
6.0         2635
8.0         2399
3.0         2215
          ...
27.0           2
205.0          1
38.0           1
274.0          1
200.0          1
Name: policycount, Length: 72, dtype: int64

policyeffectivedate
2015-11-26    4469
2015-11-25    4388
2015-11-27    3720
2015-12-02    3492
2015-12-03    3091
              ...
2019-12-06       1
2019-12-05       1
2019-11-25       1
2019-12-17       1
2020-02-02       1
Name: policyeffectivedate, Length: 3982, dtype: int64

policyterminationdate
2016-11-26    4377
2016-11-25    4286
2016-11-27    3633
2016-12-02    3406
2016-11-28    3036
              ...
2020-12-05       1
2020-12-06       1
2020-12-09       1
2020-11-29       1
2020-12-17       1
Name: policyterminationdate, Length: 4344, dtype: int64

policytermindicator
1.0    2772715
9.0          1
Name: policytermindicator, dtype: int64

postfirmconstructionindicator
N    1724235
Y    1046563
Name: postfirmconstructionindicator, dtype: int64

primaryresidenceindicator
Y    1971713
N     800981
Name: primaryresidenceindicator, dtype: int64

propertystate
CA    2772717
Name: propertystate, dtype: int64

reportedzipcode
95835    113409
95833     90528
95831     64005
95834     62649
95991     34059
          ...
94593         1
92848         1
95429         1
95865         1
93628         1
Name: reportedzipcode, Length: 1964, dtype: int64

ratemethod
1    1236591
7    1060442
B     160374
Q     111162
P      38360
2      27018
W      18214
8       2396
9       1919
S       1583
E       1039
5        456
6        278
A        149
F         44
T         38
3         33
4          3
Name: ratemethod, dtype: int64

regularemergencyprogramindicator
R    2772716
E          1
Name: regularemergencyprogramindicator, dtype: int64

reportedcity
SACRAMENTO             543458
SAN JOSE                75865
STOCKTON                66479
VISALIA                 64812
LOS ANGELES             64576
                        ...
OXANARD                     1
SOUTH SAN FRANCISCA         1
PALOMAR MTN                 1
NACRAMENTO                  1
E NICOLAUS                  1
Name: reportedcity, Length: 2582, dtype: int64

smallbusinessindicatorbuilding
N    969803
Y     12954
Name: smallbusinessindicatorbuilding, dtype: int64

totalbuildinginsurancecoverage
250000.0     1708256
500000.0      101938
200000.0       98117
150000.0       60946
100000.0       39548
              ...
973500.0           1
1673400.0          1
394700.0           1
5227500.0          1
295500.0           1
Name: totalbuildinginsurancecoverage, Length: 6385, dtype: int64

totalcontentsinsurancecoverage
0.0         1181191
100000.0    1093832
80000.0       84953
50000.0       57267
60000.0       51156
             ...
250700.0          1
116400.0          1
304700.0          1
425100.0          1
153800.0          1
Name: totalcontentsinsurancecoverage, Length: 2309, dtype: int64

totalinsurancepremiumofthepolicy
348.0      364965
335.0      135700
392.0      133295
345.0      128290
390.0       36101
            ...
15051.0         1
11796.0         1
13449.0         1
19883.0         1
8585.0          1
Name: totalinsurancepremiumofthepolicy, Length: 10791, dtype: int64

In [15]:
df.columns

Index(['agriculturestructureindicator', 'basefloodelevation',
       'basementenclosurecrawlspacetype', 'cancellationdateoffloodpolicy',
       'censustract', 'condominiumindicator', 'construction', 'countycode',
       'crsdiscount', 'deductibleamountinbuildingcoverage',
       'deductibleamountincontentscoverage', 'elevatedbuildingindicator',
       'elevationcertificateindicator', 'elevationdifference',
       'federalpolicyfee', 'floodzone', 'hfiaasurcharge',
       'houseofworshipindicator', 'latitude', 'locationofcontents',
       'longitude', 'lowestadjacentgrade', 'lowestfloorelevation',
       'nonprofitindicator', 'numberoffloorsininsuredbuilding',
       'obstructiontype', 'occupancytype', 'originalconstructiondate',
       'originalnbdate', 'policycost', 'policycount', 'policyeffectivedate',
       'policyterminationdate', 'policytermindicator',
       'postfirmconstructionindicator', 'primaryresidenceindicator',
       'propertystate', 'reportedzipcode', 'ratemethod',
       'regularemergencyprogramindicator', 'reportedcity',
       'smallbusinessindicatorbuilding', 'totalbuildinginsurancecoverage',
       'totalcontentsinsurancecoverage', 'totalinsurancepremiumofthepolicy'],
      dtype='object')

In [16]:
df.drop(columns=['agriculturestructureindicator', 'basefloodelevation', 'basementenclosurecrawlspacetype', 'cancellationdateoffloodpolicy',
       'censustract', 'condominiumindicator', 'construction',  'deductibleamountinbuildingcoverage',
       'deductibleamountincontentscoverage', 'elevatedbuildingindicator',
       'elevationcertificateindicator', 'elevationdifference',
       'federalpolicyfee','hfiaasurcharge',
       'houseofworshipindicator', 'latitude', 'locationofcontents',
       'longitude', 'lowestadjacentgrade', 'lowestfloorelevation',
       'nonprofitindicator', 'numberoffloorsininsuredbuilding',
       'obstructiontype', 'occupancytype', 'originalconstructiondate','originalnbdate', 'policycount','policyterminationdate', 'policytermindicator',
       'postfirmconstructionindicator', 'primaryresidenceindicator',
       'propertystate', 'reportedzipcode', 'ratemethod',
       'regularemergencyprogramindicator', 'reportedcity',
       'smallbusinessindicatorbuilding','totalbuildinginsurancecoverage',
       'totalcontentsinsurancecoverage', 'totalinsurancepremiumofthepolicy'], inplace=True)

In [17]:
df.isna().sum()

countycode             0
crsdiscount            0
floodzone              0
policycost             0
policyeffectivedate    0
dtype: int64

In [18]:
df

         countycode  crsdiscount floodzone  policycost policyeffectivedate
0            6067.0         0.00         X       348.0          2009-12-07
1            6067.0         0.00         X       348.0          2009-01-26
2            6107.0         0.00       AHB       327.0          2009-04-23
3            6077.0         0.00         B       296.0          2009-10-12
4            6037.0         0.15        AE       378.0          2009-03-06
...             ...          ...       ...         ...                 ...
2772712      6085.0         0.15       AOB       373.0          2019-09-23
2772713      6067.0         0.00       A99       482.0          2019-04-20
2772714      6073.0         0.10         C      1535.0          2019-04-04
2772715      6037.0         0.00         X       705.0          2019-02-27
2772716      6059.0         0.00         X       607.0          2020-02-02

[2772717 rows x 5 columns]

In [19]:
df['policyeffectivedate']= df['policyeffectivedate'].astype('datetime64[ns]')
df['year']= df['policyeffectivedate'].dt.year
df['year'].value_counts()

2015    296108
2009    288010
2010    284082
2011    276008
2012    264737
2016    257493
2013    253190
2017    242916
2014    240495
2018    226250
2019    143427
2020         1
Name: year, dtype: int64

In [20]:
dff= pd.read_csv(r"C:\Users\31405.ISBDOMAIN1\Downloads\FimaNfipClaims.csv", low_memory=False)
dff

,agricultureStructureIndicator,asOfDate,baseFloodElevation,reportedCity,condominiumIndicator,policyCount,countyCode,communityRatingSystemDiscount,dateOfLoss,elevatedBuildingIndicator,...,rateMethod,smallBusinessIndicatorBuilding,state,totalBuildingInsuranceCoverage,totalContentsInsuranceCoverage,yearOfLoss,primaryResidence,id,basementEnclosureCrawlspace,reportedZipcode
0,0.0,2021-07-24T00:00:00.000Z,NaN,Temporarily Unavailable,N,1.0,24033.0,5.0,2007-01-01T00:00:00.000Z,0.0,...,7,0.0,MD,100000.0,40000.0,2007,1.0,babe8abc-eae6-49f4-a5d6-b892b1087a45,1.0,20745.0
1,0.0,2021-07-24T00:00:00.000Z,NaN,Temporarily Unavailable,N,1.0,30009.0,NaN,2011-07-12T00:00:00.000Z,1.0,...,1,0.0,MT,150000.0,0.0,2011,1.0,dbc2a6cc-192f-47ee-bd3c-e76bcc6a2350,NaN,59068.0
2,0.0,2021-11-20T00:00:00.000Z,50.0,Temporarily Unavailable,N,1.0,48201.0,5.0,2001-06-09T00:00:00.000Z,0.0,...,1,0.0,TX,25000.0,25000.0,2001,1.0,547d731b-b35f-4d60-a903-15cc8a4d12df,NaN,77025.0
3,0.0,2021-11-20T00:00:00.000Z,9.0,Temporarily Unavailable,N,1.0,12103.0,5.0,1996-10-07T00:00:00.000Z,1.0,...,1,0.0,FL,150000.0,35000.0,1996,1.0,18e7a2e8-5b52-4cdd-82a2-9112dbbc953b,NaN,33702.0
4,0.0,2021-11-20T00:00:00.000Z,NaN,Temporarily Unavailable,N,1.0,24029.0,NaN,2003-09-19T00:00:00.000Z,1.0,...,1,0.0,MD,75000.0,10000.0,2003,0.0,40c5393a-03a4-41ed-8fb3-4b3de1e28534,NaN,21620.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2570084,0.0,2022-04-06T00:00:00.000Z,8.0,Temporarily Unavailable,N,1.0,37055.0,6.0,2021-11-06T00:00:00.000Z,1.0,...,1,0.0,NC,250000.0,70400.0,2021,0.0,cdd80c93-31a6-44c7-b173-4d8e27cf1d03,NaN,27968.0
2570085,0.0,2022-04-02T00:00:00.000Z,NaN,Temporarily Unavailable,N,1.0,26111.0,5.0,2017-06-23T00:00:00.000Z,0.0,...,1,0.0,MI,158000.0,0.0,2017,1.0,422408fb-e1dc-4735-92b3-1e311958a7c0,2.0,48640.0
2570086,0.0,2022-04-02T00:00:00.000Z,NaN,Temporarily Unavailable,N,1.0,37191.0,8.0,2018-09-18T00:00:00.000Z,0.0,...,1,0.0,NC,177800.0,31500.0,2018,1.0,70d56b85-759a-4642-883e-815a131b8169,NaN,27530.0
2570087,0.0,2022-04-02T00:00:00.000Z,14.0,Temporarily Unavailable,N,1.0,37141.0,7.0,2018-09-14T00:00:00.000Z,1.0,...,1,0.0,NC,250000.0,100000.0,2018,0.0,60ba5718-70bd-4d44-b7fa-af66ab67d02f,2.0,28445.0
2570088,0.0,2022-04-09T00:00:00.000Z,NaN,Temporarily Unavailable,N,1.0,34025.0,NaN,2012-07-28T00:00:00.000Z,0.0,...,7,0.0,NJ,250000.0,100000.0,2012,0.0,be9b588c-cc2b-4c81-a66e-4d8f6cac0ea4,NaN,8736.0

In [21]:
dff['asOfDate']= pd.to_datetime(dff['asOfDate'])
dff['year']= dff['asOfDate'].dt.year
dff['year'].value_counts()

2021    2047132
2022     522957
Name: year, dtype: int64

In [22]:
df

,countycode,crsdiscount,floodzone,policycost,policyeffectivedate,year
0,6067.0,0.00,X,348.0,2009-12-07,2009
1,6067.0,0.00,X,348.0,2009-01-26,2009
2,6107.0,0.00,AHB,327.0,2009-04-23,2009
3,6077.0,0.00,B,296.0,2009-10-12,2009
4,6037.0,0.15,AE,378.0,2009-03-06,2009
...,...,...,...,...,...,...
2772712,6085.0,0.15,AOB,373.0,2019-09-23,2019
2772713,6067.0,0.00,A99,482.0,2019-04-20,2019
2772714,6073.0,0.10,C,1535.0,2019-04-04,2019
2772715,6037.0,0.00,X,705.0,2019-02-27,2019
2772716,6059.0,0.00,X,607.0,2020-02-02,2020